use_frameworks!

platform :ios, '10.0'

target 'NorneTestSDWebImage_Example' do
  pod 'NorneTestSDWebImage', :path => '../'

  target 'NorneTestSDWebImage_Tests' do
    inherit! :search_paths

    
  end
end
